# This docker-compose file is meant to be run from project root folder
# which is outside of database folder.

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=census-app
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
