# On you termonal please run command:
# docker compose up -d

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=census-app
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  # Swagger server is work in progress
  # swagger_ui:
  #   image: "swaggerapi/swagger-ui"
  #   container_name: "swagger-ui"
  #   ports:
  #     - 80:3001
  #   environment:
  #     - BASE_URL=/swagger
  #     - SWAGGER_JSON=/swagger/swagger.json
  #   volumes:
  #     - swagger-ui:/foo swaggerapi/swagger-ui

volumes:
  postgres-data:
  # swagger-ui:
