import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  cookies();
  const user = (await auth())?.user || undefined;

  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar user={user} />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
