import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { auth } from "@/auth";
import { cookies } from "next/headers";
import { AuthUser } from "@/types/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  cookies();
  const session = await auth();
  const user = session?.user as AuthUser;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-full">
          <Navbar user={user} />
          {children}
        </div>
      </body>
    </html>
  );
}
